# Generated by Django 3.2.25 on 2024-06-20 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_description'),
        ('profiles', '0005_auto_20240620_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='wished_item',
            field=models.ManyToManyField(blank=True, related_name='user_wishlist', to='products.Product'),
        ),
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
