# Generated by Django 3.2.25 on 2024-06-20 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20240620_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='wished_item',
        ),
    ]
