# Generated by Django 3.2.25 on 2024-06-15 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderlineitem',
            old_name='uantity',
            new_name='quantity',
        ),
    ]
