# Generated by Django 3.2.25 on 2024-05-30 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colour', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='colour',
        ),
    ]
