# Generated by Django 3.2.25 on 2024-05-30 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20240530_1940'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colour',
            old_name='colour',
            new_name='name',
        ),
    ]
