# Generated by Django 3.2.25 on 2024-05-30 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_colour_colour_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='colour',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.colour'),
        ),
    ]
