# Generated by Django 3.2.25 on 2024-05-30 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_product_colour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='colour',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Colour',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
