# Generated by Django 3.2.25 on 2024-06-14 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general', models.CharField(max_length=100)),
                ('materials', models.CharField(max_length=100)),
                ('production', models.CharField(max_length=100)),
                ('shipping', models.CharField(max_length=100)),
                ('returns', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='subject',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='info.subject'),
        ),
        migrations.DeleteModel(
            name='Faq',
        ),
    ]
