# Generated by Django 3.2.25 on 2024-06-14 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_auto_20240614_1911'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='general',
            new_name='subject',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='materials',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='production',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='returns',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='shipping',
        ),
    ]
