# Generated by Django 3.2.25 on 2024-06-14 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_auto_20240614_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='accord',
            field=models.CharField(default='', max_length=10),
        ),
    ]
