# Generated by Django 3.2.25 on 2024-06-18 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_subject_accord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='accord',
        ),
        migrations.AddField(
            model_name='subject',
            name='friendly_name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
