# Generated by Django 3.2.25 on 2024-06-18 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_auto_20240618_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='friendly_name',
        ),
        migrations.AddField(
            model_name='subject',
            name='friendly_name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
