# Generated by Django 3.2.25 on 2024-06-18 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0007_auto_20240618_1854'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='subject',
            new_name='subject_name',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='subject',
            new_name='subject_name',
        ),
    ]
