# Generated by Django 3.2.25 on 2024-06-18 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0008_auto_20240618_2037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='subject_name',
            new_name='subject',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='subject_name',
            new_name='subject',
        ),
    ]
