# Generated by Django 3.2.25 on 2024-06-19 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0010_remove_subject_friendly_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='friendly_name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
