# Generated by Django 3.2.25 on 2024-06-20 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_remove_userprofile_wished_item'),
        ('products', '0005_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='wished_item',
            field=models.ManyToManyField(blank=True, related_name='user_wishlist', to='profiles.UserProfile'),
        ),
    ]
