# Generated by Django 3.2.25 on 2024-06-20 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_wished_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='wished_item',
            new_name='favourited_by',
        ),
    ]
